name: Test Secrets Access

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Secret is Set
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "Secret SONAR_TOKEN is not set or is empty."
            exit 1
          else
            echo "Secret SONAR_TOKEN is set."
          fi
