name: Test Secrets Access

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Access
        run: echo "Secret Value: ${{ secrets.SONAR_TOKEN }}"
